### ISSUE TITLE
Doesn't work in NodeJS, no Proxy

### ISSUE THREAD

**Issue by mearns** [lachlanhunt/arrayslice#2]
Looks like a cool project, but I can't get it to work, at least in Node v5.6.0. Not sure what `Proxy` is supposed to be, but it doesn't exist. Running the following script:

``` javascript
"use strict";

const ArraySlice = require('arrayslice');
let a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
let b = ArraySlice(a, 3, 7);
```

I get the following error:

```
/sandbox/node_modules/arrayslice/lib/ArraySlice.js:152
    let proxy = new Proxy(o, handler);
                    ^

ReferenceError: Proxy is not defined
    at ArraySlice (/sandbox/node_modules/arrayslice/lib/ArraySlice.js:152:18)
    at Object.<anonymous> (/sandbox/test.js:5:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
```

This occurs with version 0.1.0 of the library.

**Comment by mearns** [comment]
I just found Proxy on MDN, unfortunately I can't find any indication that Node supports it. That being the cast (unless you have a work around), I'm not sure if it's appropriate to list it in the npmjs.com registry, and maybe unlisting it is the only resolution required for the issue.

**Comment by lachlanhunt** [comment]
You need to use Node 6.

**Comment by mearns** [comment]
Shoot. Sorry, I thought I was using Node 6. I was not.
